// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbwpyfclwkfdtnpdpayf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1id3B5ZmNsd2tmZHRucGRwYXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDY3NDgsImV4cCI6MjA3MzM4Mjc0OH0.Cdgr86EsJwQhsX9D-a-7nFSG7KJzpCEjw4v4A6hUbZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});